# Generated by Django 3.1.5 on 2021-01-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_deposit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_deposit.instrument')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_service.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConsumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_deposit.consumable')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_service.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='consumables',
            field=models.ManyToManyField(through='app_service.ServiceConsumable', to='app_deposit.Consumable'),
        ),
        migrations.AddField(
            model_name='service',
            name='instruments',
            field=models.ManyToManyField(through='app_service.ServiceInstrument', to='app_deposit.Instrument'),
        ),
    ]
