# Generated by Django 3.1.5 on 2021-03-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0003_auto_20210306_1849'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
    ]
