# Generated by Django 3.1.5 on 2021-04-18 19:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_entities', '0005_itemuserattachment_utiluserattachment'),
        ('app_projects', '0006_auto_20210330_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProjectAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_attachment_set', to='app_entities.item')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_attachment_set', to='app_projects.project')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
