# Generated by Django 3.1.5 on 2021-04-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0007_itemprojectattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemProjectAttachment',
        ),
    ]
