# Generated by Django 3.1.5 on 2021-04-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0009_auto_20210425_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeuserprojectsupply',
            name='project',
        ),
        migrations.RemoveField(
            model_name='timeuserprojectsupply',
            name='user',
        ),
        migrations.DeleteModel(
            name='ItemUserProjectSupply',
        ),
        migrations.DeleteModel(
            name='TimeUserProjectSupply',
        ),
    ]
