# Generated by Django 3.1.5 on 2021-02-24 20:12

import app_accounts.managers
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('fullname', models.CharField(blank=True, max_length=128, verbose_name='fullname')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('last_login', models.DateTimeField(null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('idnp', models.CharField(blank=True, max_length=20, null=True, verbose_name='idnp')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], default='MALE', max_length=10, verbose_name='gender')),
                ('is_admin_account', models.BooleanField(default=False, verbose_name='is admin')),
                ('is_staff_account', models.BooleanField(default=False, verbose_name='is staff')),
                ('is_agent_account', models.BooleanField(default=False, verbose_name='is agent')),
                ('is_basic_account', models.BooleanField(default=False, verbose_name='is basic')),
                ('hour_price', models.FloatField(default=100, verbose_name='hour price')),
                ('agent_rate', models.PositiveIntegerField(default=10, verbose_name='agent rate')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', app_accounts.managers.UserManager()),
            ],
        ),
    ]
