# Generated by Django 3.1.5 on 2021-02-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(gender__in=['MALE', 'FEMALE']), name='check_user_gender'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(agent_rate__lte=100), name='check_user_agent_rate'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(hour_price__gte=0), name='check_user_hour_price'),
        ),
    ]
