# Generated by Django 3.1.5 on 2021-02-27 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_entities', '0002_auto_20210224_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='util',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserUtil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utils', to=settings.AUTH_USER_MODEL)),
                ('util', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_use', to='app_entities.util')),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_use', to='app_entities.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='userutil',
            constraint=models.UniqueConstraint(fields=('util', 'user'), name='unique_user_util'),
        ),
        migrations.AddConstraint(
            model_name='useritem',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='unique_user_item'),
        ),
    ]
