# Generated by Django 3.1.5 on 2021-03-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_entities', '0003_auto_20210227_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sell_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(check=models.Q(price__gte=0), name='item_sell_price'),
        ),
    ]
