# Generated by Django 3.1.5 on 2021-04-20 17:15

from django.db import migrations, models
import django.db.models.aggregates
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('app_entities', '0005_itemuserattachment_utiluserattachment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemuserattachment',
            constraint=models.CheckConstraint(check=models.Q(count__lte=django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('item__count'), '-', django.db.models.aggregates.Sum('item__user_attachment__count'))), name='item_user_transaction'),
        ),
    ]
