# Generated by Django 3.1.5 on 2021-04-25 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_entities', '0007_auto_20210425_1024'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='util',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='useritem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_attachment', to='app_entities.item'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_attachment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useritemsupply',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_supply_set', to='app_entities.item'),
        ),
        migrations.AlterField(
            model_name='userutil',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='util_attachment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userutil',
            name='util',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_attachment', to='app_entities.util'),
        ),
        migrations.AlterField(
            model_name='userutilsupply',
            name='util',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_supply_set', to='app_entities.util'),
        ),
    ]
