# Generated by Django 3.1.5 on 2021-02-16 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_inventory', '0002_auto_20210202_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='users',
            field=models.ManyToManyField(through='app_inventory.UserInstrument', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='users',
            field=models.ManyToManyField(through='app_inventory.UserMaterial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userinstrument',
            unique_together={('user', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='usermaterial',
            unique_together={('user', 'item')},
        ),
    ]
